#   _____
#  / ___/
# / /__   Credits
# \___/

settings:
  slots: 27
  storage:
    type: SQLITE
    database: credits
    host: 127.0.0.1
    port: 27017
    username: ''
    password: ''
items:
  worldedit:
    cost: 100
    limit: -1
    item:
      name: '&a&lWorldEdit &a(30m)'
      lore:
        - ''
        - '&7Purchasing this will provide'
        - '&730 minutes of WorldEdit usage.'
        - ''
        - '&7Cost: &e{cost} Credits'
      material: WOOD_AXE
    actions:
      - '[message] &7You purchased WorldEdit.'
message:
  header: '&7'
  footer: '&7'
  prefix: '&8[&eRC&8]&7'
  no_permission: '{1} You don''t have permission to use that.'
  invalid_command: '{1} Unknown sub-command, try &e/credits&7.'
  players_only: '{1} This command can only be used in-game.'
  usage: '{1} Usage: &e/credits {2}&7.'
  must_be_a_number: '{1} You must specify a valid number.'
  reload: '{1} Configuration reloaded.'
  command_format: ' &6/credits &e{0} &7({1})'
  balance: '{1} Credits: &e{2}'
  set_balance: '{1} You set &6{2}''s &7balance to &e{3}&7.'
  reset_item_count: '{1} You reset &6{2}''s &7purchase count for the &e{3} &7shop.'
  no_item_found: '{1} No shop item was found by the id ''&e{2}&7''.'
  gui_title: 'Credits Shop (Balance: {1})'
  cannot_afford: '{1} &7You need &6{2} &7more credits to purchase this item.'
  purchased: '{1} &7You''ve spent &6{2} &7credits and now have &e{3} &7left.'
