name: ${plugin}
version: ${project.version}
main: ${package}
author: Chazza
website: https://chazza.net/
description: "The ultimate way to make your server stand out from the rest."
softdepend: ["PlaceholderAPI", "WorldGuard"]

commands:
  credits:
    description: ${plugin} commands
    usage: ""
    aliases: ["c"]

permissions:
  credits.give:
    description: Give yourself or a player a levelling tool
  credits.reload:
    description: Reload the configuration file into memory
  credits.help:
    description: View commands you have access to within the plugin
  credits.info:
    description: View information about the plugin
    default: true
  credits.xp:
    description: View yourself or another players xp amount
    default: true