name: ${plugin}
version: ${project.version}
main: ${package}
author: "Felux"
website: https://felux.io/
description: "An all-in-one credit plugin solution with shop support."
softdepend: ["PlaceholderAPI"]

commands:
  credits:
    description: ${plugin} commands
    usage: ""
    aliases: ["c", "credit", "royalcredits"]

permissions:
  credits.set:
    description: Set a players balance.
  credits.reload:
    description: Reload plugin.
  credits.shop:
    description: View the shop.
    default: true
  credits.balance:
    description: View balance.
    default: true
  credits.reset:
    description: Reset a players balance.
  credits.add:
    description: Add to a players balance.
